### ISSUE TITLE
Demos Needed

### ISSUE THREAD

**Issue by prince272** [wilsonrivera/scalider-v2#1]
Any demos  showing how to use the Scalider.AspNetCore.Navigation. Please

**Comment by wilsonrivera** [comment]
Hello,

Sorry for the delay and thank you for your feedback, I cobbled together a quick demo for it, you can see it on the demo/WebNavigationDemo project.

I plan to write a documentation too. Any question or comment I'm more than happy to listen to!

**Comment by prince272** [comment]
thanks fot your responds. But no more questions for now. I will take a look
at the demo.
